/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    Loadinganimation: typeof import('./components/LoadingAnimation/loadinganimation.vue')['default']
    Pagination: typeof import('./components/Pagination/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table/table.vue')['default']
  }
}
